---
- name: Update n1 server
  hosts: n1
  

  tasks:
  - name: Create Directory
    file: 
      name: /home/centos/new_dir
      state: directory

  tasks:
  - name: Create Directory
    file: 
      name: /home/centos/new_dir_1
      state: directory      

- name: Update n2 server
  hosts: n2
  
  tasks:
  - name: Create Directory
    file: 
      name: /home/centos/new_dir_1
      state: directory

  tasks:
  - name: Create Directory
    file: 
      name: /home/centos/new_dir_2
      state: directory

- name: Update group 1 server
  hosts: g1
  
  tasks:
  - name: Create Directory
    file: 
      name: /home/centos/new_dir_group1
      state: directory
  tasks:
  - name: Create Directory
    file: 
      name: /home/centos/new_dir_group2
      state: directory                
...
